name: hono-app

services:
  server:
    container_name: hono-app-server
    build:
      context: .
      dockerfile: Dockerfile
    mem_limit: 1G
    restart: always
    ports:
      - 127.0.0.1:3030:3030
    env_file:
      - path: ".env"
        required: true