### Register
POST http://127.0.0.1:3030/api/v1/register HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "password123"
}

### Login
# @name login
POST http://127.0.0.1:3030/api/v1/login HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "username": "user",
  "password": "password123"
}

###
@refresh_token = {{login.response.body.data.refresh_token}}

### Refresh token
# @name getToken
GET http://127.0.0.1:3030/api/v1/token HTTP/1.1
Authorization: Bearer {{refresh_token}}

###
@token = {{getToken.response.body.data.token}}

### Get user info
GET http://127.0.0.1:3030/api/v1/user HTTP/1.1
Authorization: Bearer {{token}}